# pylint: disable=pointless-statement,missing-module-docstring,duplicate-code
{
    "name": "Custom UI in odoo web",
    "version": "1.0.0",
    "category": "tools",
    "summary": "Custom UI in odoo web",
    "description": "Custom UI in odoo web",
    "sequence": "1",
    "website": "https://www.cosmosmm.com",
    "author": "Lwin Maung Maung",
    "maintainer": "lwinmaungmaung@cosmosmm.com",
    "license": "LGPL-3",
    "support": "lwinmaungmaung@cosmosmm.com",
    "depends": ["web"],
    "demo": [],
    "data": [],
    "application": True,
    "installable": True,
    "assets": {"web.assets_backend": ["web_custom_ui/static/src/css/btn_size.css"]},
}
