# pylint: disable=pointless-statement,missing-module-docstring,duplicate-code
{
    "name": "Medical Record System Lab",
    "version": "1.0.0",
    "category": "medical",
    "summary": "Medical Record System Lab",
    "description": "Medical Record System Lab",
    "sequence": "1",
    "website": "https://www.cosmosmm.com",
    "author": "Lwin Maung Maung",
    "maintainer": "lwinmaungmaung@cosmosmm.com",
    "license": "LGPL-3",
    "support": "lwinmaungmaung@cosmosmm.com",
    "depends": ["mrs_mrs", "object_storage"],
    "demo": [],
    "data": [
        "security/ir.model.access.csv",
        "views/lab_test_type_view.xml",
        "views/lab_view.xml",
        "views/visit_lab_view.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
