# pylint: disable=pointless-statement,missing-module-docstring,duplicate-code
{
    "name": "Medical Record System Immunization",
    "version": "1.0.0",
    "category": "medical",
    "summary": "Medical Record System Immunization",
    "description": "Medical Record System Immunization",
    "sequence": "1",
    "website": "https://www.cosmosmm.com",
    "author": "Lwin Maung Maung",
    "maintainer": "lwinmaungmaung@cosmosmm.com",
    "license": "LGPL-3",
    "support": "lwinmaungmaung@cosmosmm.com",
    "depends": ["mrs_mrs", "mrs_allergy"],
    "demo": [],
    "data": [
        "security/ir.model.access.csv",
        "views/immunization_view.xml",
        "views/visit_immunization_view.xml",
        "views/visit_view.xml",
        "views/res_partner_view.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
